sources:
  - name: Donats
    handler:
      graphql:
        endpoint: http://localhost:4000/graphql
transforms:
  - rename:
      mode: bare | wrap
      renames:
        - from:
            type: Query
            field: donuts
          to:
            type: Query
            field: donuts2
  - namingConvention:
      fieldNames: snakeCase
